# Generated by Django 3.2.9 on 2021-11-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(null=True)),
                ('negotiation', models.IntegerField()),
                ('archived', models.IntegerField()),
                ('purchaser_id', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('published_date', models.IntegerField(default=20210101)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Książki'), ('C', 'Komiksy'), ('M', 'Czasopisma'), ('A', 'Audiobooki'), ('E', 'E-booki'), ('CD', 'Płyty CD'), ('W', 'Płyty winylowe')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('N', 'Nowy'), ('U', 'Używany'), ('D', 'Uszkodzony'), ('E', 'Powystawowy')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('permission', models.IntegerField()),
                ('logged_in', models.IntegerField()),
                ('mean_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('D', 'dolnośląskie'), ('C', 'kujawsko-pomorskie'), ('L', 'lubelskie'), ('F', 'lubuskie'), ('E', 'łódzkie'), ('K', 'małopolskie'), ('W', 'mazowieckie'), ('O', 'opolskie'), ('R', 'podkarpackie'), ('B', 'podlaskie'), ('G', 'pomorskie'), ('S', 'śląskie'), ('T', 'świętokrzyskie'), ('N', 'warmińsko-mazurskie'), ('P', 'wielkopolskie'), ('Z', 'zachodniopomorskie')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('reviewer', models.ManyToManyField(related_name='reviewer', to='swAPP.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swAPP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ManyToManyField(to='swAPP.Announcement')),
                ('user', models.ManyToManyField(to='swAPP.User')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(related_name='followed', to='swAPP.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swAPP.user')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swAPP.category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swAPP.genre'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swAPP.status'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swAPP.user'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swAPP.voivodeship'),
        ),
    ]
