# Generated by Django 3.2.9 on 2021-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swAPP', '0003_alter_user_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
